# Generated by Django 4.2.16 on 2024-11-16 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=512)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('validade', models.DateField(default=datetime.date.today)),
                ('consumido_em', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
