# Generated by Django 4.2.16 on 2024-11-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='congelado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.tag'),
        ),
    ]
