# Generated by Django 4.2.16 on 2024-11-17 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produto_descartado_em'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='consumido_em',
            new_name='removido_em',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='descartado_em',
        ),
    ]
