# Generated by Django 4.2.16 on 2024-11-17 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_consumido_em_produto_removido_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='descricao',
        ),
    ]
